image: nobuhito/gae-go-alpine

before_script:
  - go get github.com/gorilla/mux
  - go get github.com/favclip/testerator
  - go get github.com/mjibson/goon
  - go get github.com/satori/go.uuid
  - go get cloud.google.com/go/storage

stages:
  - test

test:
  stage: test
  script: /google-cloud-sdk/platform/google_appengine/goapp test
